# Generated by Django 4.2 on 2023-04-14 23:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(choices=[('H', 'Hearts'), ('D', 'Diamonds'), ('C', 'Clubs'), ('S', 'Spades')], max_length=1)),
                ('rank', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('J', 'Jack'), ('Q', 'Queen'), ('K', 'King'), ('A', 'Ace')], max_length=2)),
                ('hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dealer', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('bet_amount', models.PositiveIntegerField(default=0)),
                ('chips', models.PositiveIntegerField(default=0)),
                ('is_bust', models.BooleanField(default=True)),
                ('cards', models.ManyToManyField(blank=True, to='game.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_code', models.CharField(max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_bet', models.IntegerField(default=1)),
                ('max_bet', models.IntegerField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('deck', models.TextField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to=settings.AUTH_USER_MODEL)),
                ('dealer_hand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dealer_hand', to='game.hand')),
                ('hands', models.ManyToManyField(blank=True, related_name='hands', to='game.hand')),
                ('players', models.ManyToManyField(related_name='games_joined', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
