# Generated by Django 4.2 on 2023-04-17 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_hand_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='dealer_hand',
        ),
    ]
