# Generated by Django 4.2 on 2023-04-17 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_game_dealer_hand'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='game',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='player_hands', to='game.game'),
            preserve_default=False,
        ),
    ]
