# Generated by Django 4.2 on 2023-04-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_hand_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='is_bust',
            field=models.BooleanField(default=False),
        ),
    ]
