# Generated by Django 4.2 on 2023-04-17 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_hand_is_bust'),
    ]

    operations = [
        migrations.AddField(
            model_name='hand',
            name='current_total',
            field=models.IntegerField(default=0),
        ),
    ]
